export const state = () => ({
  image: {
    pic: 'profile-small-1.jpg',
    userName: 'Jhon Doe',
    accountId: 12,
  },
  Info: [
    {
      daily: [
        {
          date: 2 + ' Aug ' + 2020,
          details: [
            {
              name: 'Onyenekwe Emeka Francis',
              paid: true,
              accountId: 1,
              category: 'Transfer',
              recieved: false,
              time: 12 + ':' + 26 + ' PM',
              amount: 5000,
            },
            {
              name: 'Onyenekwe Chinedu Henry',
              paid: false,
              accountId: 2,
              category: 'Transfer',
              recieved: true,
              time: 12 + ':' + 40 + ' PM',
              amount: 16000,
            },
            {
              name: 'Onyenekwe Ordi Kenneth',
              paid: true,
              accountId: 3,
              category: 'Transfer',
              recieved: false,
              time: 1 + ' PM',
              amount: 10000,
            },
          ],
        },

        {
          date: 3 + ' Aug ' + 2020,
          details: [
            {
              name: 'Onyenekwe Uche Franklin',
              paid: false,
              accountId: 4,
              category: 'Transfer',
              recieved: true,
              time: 12 + ':' + 46 + ' PM',
              amount: 5000,
            },
            {
              name: 'Onyenekwe Chizara Elizabeth',
              paid: true,
              accountId: 5,
              category: 'Transfer',
              recieved: false,
              time: 1 + ':' + 30 + ' PM',
              amount: 15000,
            },
            {
              name: 'Onyenekwe Chinwe Pauline',
              paid: false,
              accountId: 6,
              category: 'Transfer',
              recieved: true,
              time: 2 + ':' + 55 + ' PM',
              amount: 9000,
            },
          ],
        },

        {
          date: 4 + ' Aug ' + 2020,
          details: [
            {
              name: 'Onyenekwe Hycienth Ifeanyi',
              paid: true,
              accountId: 7,
              category: 'Transfer',
              recieved: false,
              time: 12 + ':' + 26 + ' PM',
              amount: 33000,
            },
            {
              name: 'Bemigho Atiene',
              paid: true,
              accountId: 8,
              category: 'Transfer',
              recieved: false,
              time: 12 + ':' + 56 + ' PM',
              amount: 10000,
            },
            {
              name: 'Ejimofor Hannah',
              paid: false,
              accountId: 9,
              category: 'Transfer',
              recieved: true,
              time: 1 + ':' + 30 + ' PM',
              amount: 5000,
            },
          ],
        },
      ],
    },
  ],
  details: [
    {
      date: 2 + ' Aug ' + 2020,
      name: 'Onyenekwe Emeka Francis',
      paid: true,
      accountId: 1,
      category: 'Transfer',
      recieved: false,
      time: 12 + ':' + 26 + ' PM',
      amount: 5000,
    },
    {
      date: 2 + ' Aug ' + 2020,
      name: 'Onyenekwe Chinedu Henry',
      paid: false,
      accountId: 2,
      category: 'Transfer',
      recieved: true,
      time: 12 + ':' + 40 + ' PM',
      amount: 16000,
    },
    {
      date: 2 + ' Aug ' + 2020,
      name: 'Onyenekwe Ordi Kenneth',
      paid: true,
      accountId: 3,
      category: 'Transfer',
      recieved: false,
      time: 1 + ' PM',
      amount: 10000,
    },
    {
      date: 3 + ' Aug ' + 2020,
      name: 'Onyenekwe Uche Franklin',
      paid: false,
      accountId: 4,
      category: 'Transfer',
      recieved: true,
      time: 12 + ':' + 46 + ' PM',
      amount: 5000,
    },
    {
      date: 3 + ' Aug ' + 2020,
      name: 'Onyenekwe Chizara Elizabeth',
      paid: true,
      accountId: 5,
      category: 'Transfer',
      recieved: false,
      time: 1 + ':' + 30 + ' PM',
      amount: 15000,
    },
    {
      date: 3 + ' Aug ' + 2020,
      name: 'Onyenekwe Chinwe Pauline',
      paid: false,
      accountId: 6,
      category: 'Transfer',
      recieved: true,
      time: 2 + ':' + 55 + ' PM',
      amount: 9000,
    },
    {
      date: 4 + ' Aug ' + 2020,
      name: 'Onyenekwe Hycienth Ifeanyi',
      paid: true,
      accountId: 7,
      category: 'Transfer',
      recieved: false,
      time: 12 + ':' + 26 + ' PM',
      amount: 33000,
    },
    {
      date: 4 + ' Aug ' + 2020,
      name: 'Bemigho Atiene',
      paid: true,
      accountId: 8,
      category: 'Transfer',
      recieved: false,
      time: 12 + ':' + 56 + ' PM',
      amount: 10000,
    },
    {
      date: 4 + ' Aug ' + 2020,
      name: 'Ejimofor Hannah',
      paid: false,
      accountId: 9,
      category: 'Transfer',
      recieved: true,
      time: 1 + ':' + 30 + ' PM',
      amount: 5000,
    },
  ],
})
